// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmwlvapbnlkpviwwexmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtd2x2YXBibmxrcHZpd3dleG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MjkzMTMsImV4cCI6MjA1MTUwNTMxM30.xtW4EQVIG_bsoyliNcf5aXTgW15GD2VJ2E2rdQJoAKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);